/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import javax.swing.JOptionPane;
import air_quality_system.AirQualitySystem;
/**
 *
 * @author enjua
 */
public class AirQualityUI extends javax.swing.JFrame {
    private AirQualitySystem resultados = new AirQualitySystem();
    /**
     * Creates new form AirQualityUI
     */
    public AirQualityUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BannerLabel = new javax.swing.JLabel();
        InstruccionesLabel = new javax.swing.JLabel();
        ParticulasLabel = new javax.swing.JLabel();
        TemperaturaLabel = new javax.swing.JLabel();
        CO2Label = new javax.swing.JLabel();
        IconLabel = new javax.swing.JLabel();
        CalcularButton = new javax.swing.JButton();
        TemperaturaTextField = new javax.swing.JTextField();
        CO2TextField = new javax.swing.JTextField();
        ParticulasTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ResultadosTextArea = new javax.swing.JTextArea();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(33, 36, 43));
        jPanel1.setToolTipText("");
        jPanel1.setAutoscrolls(true);
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 800));

        jPanel2.setBackground(new java.awt.Color(33, 36, 43));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white), "Calcular calidad del aire", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setToolTipText("");
        jPanel2.setName(""); // NOI18N

        BannerLabel.setFont(new java.awt.Font("Consolas", 1, 48)); // NOI18N
        BannerLabel.setForeground(new java.awt.Color(255, 255, 255));
        BannerLabel.setText("CALIDAD DEL AIRE");

        InstruccionesLabel.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        InstruccionesLabel.setForeground(new java.awt.Color(204, 204, 204));
        InstruccionesLabel.setText("<html> <b>Instrucciones de uso:</b><br><br>Ingrese los valores para evaluar la calidad del aire:<br> - CO2 (0-100 ppm): Nivel de dióxido de carbono en el aire<br> - Partículas PM2.5 (0-50 μg/m³): Concentración de partículas finas<br> - Temperatura (0-40 °C): Temperatura ambiental<br><br></html>");

        ParticulasLabel.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        ParticulasLabel.setForeground(new java.awt.Color(51, 153, 255));
        ParticulasLabel.setText("Particulas:");

        TemperaturaLabel.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        TemperaturaLabel.setForeground(new java.awt.Color(0, 153, 255));
        TemperaturaLabel.setText("Temperatura:");

        CO2Label.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        CO2Label.setForeground(new java.awt.Color(0, 153, 255));
        CO2Label.setText("CO2:");

        IconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icon.png"))); // NOI18N

        CalcularButton.setBackground(new java.awt.Color(0, 153, 255));
        CalcularButton.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        CalcularButton.setForeground(new java.awt.Color(255, 255, 255));
        CalcularButton.setText("Calcular");
        CalcularButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularButtonActionPerformed(evt);
            }
        });

        TemperaturaTextField.setBackground(new java.awt.Color(33, 36, 43));
        TemperaturaTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TemperaturaTextField.setForeground(new java.awt.Color(255, 255, 255));
        TemperaturaTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TemperaturaTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TemperaturaTextFieldKeyTyped(evt);
            }
        });

        CO2TextField.setBackground(new java.awt.Color(33, 36, 43));
        CO2TextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CO2TextField.setForeground(new java.awt.Color(255, 255, 255));
        CO2TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CO2TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CO2TextFieldKeyTyped(evt);
            }
        });

        ParticulasTextField.setBackground(new java.awt.Color(33, 36, 43));
        ParticulasTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ParticulasTextField.setForeground(new java.awt.Color(255, 255, 255));
        ParticulasTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ParticulasTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ParticulasTextFieldKeyTyped(evt);
            }
        });

        ResultadosTextArea.setEditable(false);
        ResultadosTextArea.setBackground(new java.awt.Color(33, 36, 43));
        ResultadosTextArea.setColumns(20);
        ResultadosTextArea.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        ResultadosTextArea.setForeground(new java.awt.Color(255, 255, 255));
        ResultadosTextArea.setRows(5);
        jScrollPane1.setViewportView(ResultadosTextArea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InstruccionesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BannerLabel)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ParticulasLabel)
                            .addComponent(CO2Label)
                            .addComponent(TemperaturaLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(TemperaturaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CalcularButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ParticulasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CO2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(59, 59, 59)
                                .addComponent(IconLabel)))))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(BannerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(InstruccionesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CO2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CO2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ParticulasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ParticulasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(IconLabel)
                        .addGap(14, 14, 14)))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TemperaturaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TemperaturaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CalcularButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CalcularButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularButtonActionPerformed
        // TODO add your handling code here:
        try {
            double co2 = Double.parseDouble(CO2TextField.getText().replace(",", "."));
            double particulas = Double.parseDouble(ParticulasTextField.getText().replace(",", "."));
            double temperatura = Double.parseDouble(TemperaturaTextField.getText().replace(",", "."));
            
            if (co2 < 0 || co2 > 100) {
                JOptionPane.showMessageDialog(rootPane, "El CO2 debe estar entre 0 y 100");
                return;
            }
            if (particulas < 0 || particulas > 50) {
                JOptionPane.showMessageDialog(rootPane, "Las partículas deben estar entre 0 y 50");
                return;
            }
            if (temperatura < 0 || temperatura > 40) {
                JOptionPane.showMessageDialog(rootPane, "La temperatura debe estar entre 0 y 40");
                return;
            }
            
            ResultadosTextArea.setText(resultados.evaluarCalidadAire(co2, particulas, temperatura));
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Por favor complete todos los campos con valores numéricos válidos");
        }
    }//GEN-LAST:event_CalcularButtonActionPerformed

    private void CO2TextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CO2TextFieldKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Valor inválido. Ingrese solo números");
        }
    }//GEN-LAST:event_CO2TextFieldKeyTyped

    private void ParticulasTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ParticulasTextFieldKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Valor inválido. Ingrese solo números");
        }
    }//GEN-LAST:event_ParticulasTextFieldKeyTyped

    private void TemperaturaTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TemperaturaTextFieldKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Valor inválido. Ingrese solo números");
        }
    }//GEN-LAST:event_TemperaturaTextFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AirQualityUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AirQualityUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AirQualityUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AirQualityUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AirQualityUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BannerLabel;
    private javax.swing.JLabel CO2Label;
    private javax.swing.JTextField CO2TextField;
    private javax.swing.JButton CalcularButton;
    private javax.swing.JLabel IconLabel;
    private javax.swing.JLabel InstruccionesLabel;
    private javax.swing.JLabel ParticulasLabel;
    private javax.swing.JTextField ParticulasTextField;
    private javax.swing.JTextArea ResultadosTextArea;
    private javax.swing.JLabel TemperaturaLabel;
    private javax.swing.JTextField TemperaturaTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
